ryansolid/dom-expressions

packages/hyper-dom-expressions/src/index.ts
Using parcel.js with the following jsx pragma and code:
```jsx
/** @jsx h */
import h from 'solid-js/h'
import { render } from 'solid-js/dom'
render(
() => <h1>HELLO</h1>,
document.getElementById('root')
);
```
...causes it to call `h` like this:
```js
h("h1", null, "HELLO")
```
...which fails, because `props` is `null`, and is seen as being `typeof "object"`.
This commit allows `props` to be ignored if `null`, instead of being treated like an `object`.
=> Allow props to be null or undefined, for parcel.js

packages/babel-plugin-jsx-dom-expressions/src/shared/utils.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/textInterpolation/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/textInterpolation/output.js
Hi Ryan,
I had an issue where a multi-line text paragraph in my JSX source code, had its **last word of a line** and the **first word of the next line**, smushed together without any whitespace between them.
_Of course, a newline is considered whitespace in HTML. [I had to double-check!](https://developer.mozilla.org/en-US/docs/Glossary/Whitespace)_
Example:
```html
<p>sadf asdf asdf asd fas df asdf asdf asdf asdf asd fsad fas dfs adf LAST_WORD_OF_LINE
FIRST_WORD_OF_NEXT_LINE jhg jhg jhg jhg jhg jhg jhg jhg jhg jhg jhg jhg jhg jhg jhg</p>
```
...would turn into this in the DOM:
```html
<p>sadf asdf asdf asd fas df asdf asdf asdf asdf asd fsad fas dfs adf LAST_WORD_OF_LINEFIRST_WORD_OF_NEXT_LINE jhg jhg jhg jhg jhg jhg jhg jhg jhg jhg jhg jhg jhg jhg jhg</p>
```
This PR fixes that, while …
=> Fix multi-line text paragraphs

packages/babel-plugin-jsx-dom-expressions/src/shared/utils.js, packages/dom-expressions/src/runtime.js
I compared performance for `escapeHTML` function using @dougwilson's [benchmark](https://github.com/component/escape-html/blob/master/benchmark/index.js) from [escape-html](https://github.com/component/escape-html) repo.
**Before:**
**After:**
Bundle size will increase a bit but it shouldn't matter if this code is mostly used on backend side during server-side rendering where the performance is much more important.
=> Increase escapeHTML performance up to 10 times!

packages/dom-expressions/src/runtime.d.ts
Just found a [usage](https://github.com/ryansolid/solid/blob/e99f2ad590cad09a9ab1983369f097b6c16bf666/packages/solid-ssr/examples/async/index.js#L29) but not the typings:
https://github.com/ryansolid/dom-expressions/blob/ba1ea6b2d8136d9fcae412682ec162bc010f6c50/packages/dom-expressions/src/runtime.js#L329-L333
=> Typings for generateHydrationScript({ resolved })

packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/src/dom/template.js, packages/babel-plugin-jsx-dom-expressions/src/shared/postprocess.js, packages/babel-plugin-jsx-dom-expressions/src/shared/preprocess.js, packages/babel-plugin-jsx-dom-expressions/src/ssr/template.js
In 86c9ff1, state for templates and events was moved from `path.scope.data` to `path.state`. Newer versions of babel have a bug with the way that `TraversalContext`s are tracked and it can cause `path.state` to be clobbered. This issue manifests itself when other babel plugins (notably `@babel/plugin-proposal-class-properties`) are used that visit the same AST nodes. This pull request moves template and events state back to `path.scope.data`.
The issue seems to have first occurred after this https://github.com/babel/babel/pull/12302
I believe this unfinished PR will fix the `TraversalContext` bug https://github.com/babel/babel/pull/12634
=> Partially revert 86c9ff1 Add static template hoisting to SSR

packages/babel-plugin-jsx-dom-expressions/src/config.js, packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/src/dom/template.js, packages/babel-plugin-jsx-dom-expressions/src/shared/utils.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_wrapperless_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_wrapperless_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_wrapperless_fixtures__/components/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_wrapperless_fixtures__/components/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_wrapperless_fixtures__/conditionalExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_wrapperless_fixtures__/conditionalExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_wrapperless_fixtures__/fragments/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_wrapperless_fixtures__/fragments/output.js, packages/babel-plugin-jsx-dom-expressions/test/dom-wrapperless.spec.js
This generalizes babel-plugin-jsx-dom-expressions generated calls to `effect()` and `memo()`. The function names are now configurable with new options `setAttributesWrapper` (effect) and `dynamicExpressionWrapper` (memo). The plugin behavior is unchanged when the default options are used. Additionally, either option can be set to `false`, which will essentially treat expressions as if they were static and won't wrap them. 
The use case for setting the new options to `false` is to use babel-plugin-jsx-dom-expressions with a wrapperless non-reactive runtime.
I've copied a subset of relevant tests from `dom.spec.js` to `dom-wrapperless.spec.js` with the new options set to false.
=> Add setAttributesWrapper and dynamicExpressionWrapper config options

README.md, packages/dom-expressions/README.md
The `createComponent()` examples in the documentation have an unused argument `dynamicKeys`. `babel-plugin-jsx-dom-expressions` doesn't generate any calls to createComponent with this argument. I'm assuming this is from an old version.
=> Fix inaccurate docs

packages/dom-expressions/src/jsx.d.ts
- All the `aria-*` should accept string as they are HTML attributes and HTML attributes only accept strings.
- Adding `scope` attribute for `th` as per [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th)
=> Improve some typings

packages/dom-expressions/src/jsx.d.ts
As per the list of attributes defined here: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use#attributes
=> Adding missing `href` attribute to `UseSVGAttributes`

packages/dom-expressions/src/client.js
Makes it consistent with vanilla (without event delegation) and React
https://codesandbox.io/s/xenodochial-resonance-mz4hd
=> Fix events firing on disabled elements

packages/dom-expressions/src/client.js, packages/dom-expressions/test/classList.spec.jsx
This PR should fix #77 by triming classes before toggling in `toggleClassKey`
=> add trim on toggleClassKey to support trailing/leading spaces

packages/dom-expressions/src/jsx.d.ts
The `role="meter"` is woefully underused, for example for amplitude visualization or password strength - and even missing here. More under: https://w3c.github.io/aria-practices/examples/meter/meter.html
=> add missing "meter" role

packages/dom-expressions/src/jsx.d.ts
Typing details as DetailsHTMLAttributes<HTMLElement> will stop the open property from working correctly in typescript.
=> Fix typings for <details>

packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/src/shared/component.js
This PR fixes a known issue for `dom-expressions` where using non-null and type-as expressions causes `ref` property to get stripped out of the output code.
TODO
- Should I add fixtures/snapshots for the TS expressions?
=> Fix `ref` property to normalize `TsNonNullExpression` and `TsAsExpression`

packages/babel-plugin-jsx-dom-expressions/src/shared/component.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/components/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/components/output.js
Not sure if it was intended or not, but [this commit](https://github.com/ryansolid/dom-expressions/pull/99/commits/2b0b44d05ba2847c57fab25d1fa5ae21e21b1922) removed quotes in compiled JSX output for attribute names which are reserved words in javascript, like "class".
`get [class]()` without quotes is invalid syntax in chrome, so I think the quotes are necessary at least for the web. 
If it's ok to have quotes for all targets (ssr, universal?), the fix is pretty simple - revert `t.isValidIdentifier` call to the form it was before that commit - without the second `false` parameter.
=> fix: add quotes around attribute names which are reserved words in js

packages/dom-expressions/src/jsx.d.ts
The event information is found here: https://developer.mozilla.org/en-US/docs/Web/API/HTMLDetailsElement/toggle_event
It seems like react added it in a similar fashion: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2079-L2081
=> Add missing `onToggle` event to the `<details>` event

packages/dom-expressions/src/constants.js
Add `contextmenu` to `DelegatedEvents`.
This is a useful event for passing through Portals when doing custom context menus.
=> Delegate contextmenu events

packages/babel-plugin-jsx-dom-expressions/src/dom/template.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/SVG/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/components/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/conditionalExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/customElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/eventExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/fragments/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/insertChildren/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/namespaceElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/simpleElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/textInterpolation/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/SVG/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/components/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/customElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/eventExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/fragments/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/simpleElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/textInterpolation/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_wrapperless_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_wrapperless_fixtures__/components/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_wrapperless_fixtures__/conditionalExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_wrapperless_fixtures__/fragments/output.js, packages/dom-expressions/src/constants.js
When components are included in files but are unused, Terser of course removes those functions. However, the generated calls to `template` outside of that function are kept, leading to code like:
```js
template("<div></div>");
const _tmpl$2 = template('<button type="button"></button>');
```
Note the first template is not assigned to anything, but Terser preserves it just in case it has side-effects.
However, the only side-effect `template` has is creating an unparented DOM node, which is just wasteful if not removed.
Therefore, marking `template` with the leading comment `/*#__PURE__*/` allows Terser the freedom to remove calls to it if the results are unused.
Also, may want to squash this when merging.
=> Mark `template` as `#__PURE__` in generated code.

packages/dom-expressions/src/jsx.d.ts
This way, a downstream lib can add whatever methods their class lib should have. They might want, for example, to use `template` instead of `render`.
Conversation: https://discord.com/channels/722131463138705510/817960620736380928/960716685499850752
=> make JSX.ElementClass empty so that libs can define requirements

packages/dom-expressions/src/client.js, packages/dom-expressions/src/universal.js, packages/dom-expressions/test/dom/spread.spec.jsx, packages/dom-expressions/test/universal/spread.spec.jsx, packages/hyper-dom-expressions/test/hyperscript.spec.js
This fixes solid issue solidjs/solid#903
[Refs are not reactive](https://discord.com/channels/722131463138705510/722349143024205824/940407159999569970), so ref call does not need to be wrapped in the separate effect
The change I'm less confident with is that the ref now is called even if its value did not change - the ref call is moved above the `if (value === prev)` check, in both web (for spread only) and universal (always?) renderers. But this is necessary to have ref() called again after cleanup in the functional spread ( in `<span {...p()}>` in the last test )
=> move ref call outside of the spread effect

packages/dom-expressions/src/jsx.d.ts
Similar to `ElementClass`, defines it, but empty so class libs can use it. Should we add this empty? Or delete `ElementClass` instead? Having them present but empty might serve as a hint.
=> add empty ElementAttributesProperty

packages/dom-expressions/src/jsx.d.ts
Directives (`use:___`) normally have two arguments, first the element/component and second the value passed in as a JSX attribute. The existing `Directives` overloadable interface only allows checks the value / second argument.  This PR provides a new overloadable interface `DirectiveFunctions` checks both (when present), by specifying the entire function type.
Example usage:
```ts
function model(element: HTMLInputElement, value: Accessor<Signal<string>>) {
const [field, setField] = value();
createRenderEffect(() => (element.value = field()));
element.addEventListener("input", (e) => setField(e.target.value));
}
function log(element: DOMElement) {
console.log(element);
}
let num = 0;
function count() {
num++;
}
function foo(comp: number, ...args: string[]) {
}
declare module "solid-js" { …
```
=> DirectiveFunctions alternative for typing directives

packages/dom-expressions/src/client.js
- fixes a infinite recursion bug from [this commit](https://github.com/ryansolid/dom-expressions/commit/cc3437dd25a4bf9fb94381d2dacde0469a673a2e?diff=split#diff-da2a5911aa8defd1b1e3649a3b811b7e67a2a7cea695d42b24a5e4ffd2b68ebdR90)
- implements `this` value in event handlers as per  https://html.spec.whatwg.org/multipage/webappapis.html#the-event-handler-processing-algorithm
=> fix *this* in events

packages/dom-expressions/src/server.js
Calling `renderToStringAsync` prevents Node.js from exiting until the timeout has elapsed. This PR fixes the issue by clearing the timeout once `asyncWrap` is resolved.
=> Fix: Node process does not exit until timeout

packages/dom-expressions/src/client.js
The previous code uses `item.string()` which I believe is a typo. This change uses `String(item)` **directly** so it also skips checking if the type is `"string"`.
Fixes https://github.com/solidjs/solid/issues/1093
=> Fix `normalizeIncomingArray` for non-string items

packages/babel-plugin-jsx-dom-expressions/package-lock.json, packages/babel-plugin-jsx-dom-expressions/package.json
This avoids issues with yarn 2 complaining about package not providing @babel/core.
```
➤ YN0002: │ babel-plugin-jsx-dom-expressions@npm:0.33.8 doesn't provide @babel/core (p9ac8d), requested by @babel/plugin-syntax-jsx
```
See https://dev.to/arcanis/implicit-transitive-peer-dependencies-ed0 for more details.
=> Declare @babel/core as peer dependency

packages/dom-expressions/src/universal.d.ts
This PR changes the return types of `getFirstChild`, `getParentNode` and `getNextSibling` to allow `undefined` to be returned.
`undefined` is a valid case, for example, when the element being queried is the parent node, has no children, is the only child or is the last child. Solid already handles those cases properly with the right checks AFAIK.
=> Fix universal renderer types

packages/dom-expressions/src/jsx-h.d.ts, packages/dom-expressions/src/jsx.d.ts
As reported by @fabiospampinato, the types for `onAuxClick` were missing, despite the existence of [auxclick event](https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event). He wrote in #typescript:
> I don't know why, but the middle click seems to fire an "auxclick" for me, not a "click", so this feels pretty much essential. A convenience onMiddleClick might be worth exploring too.
=> Add types for onAuxClick

packages/dom-expressions/src/jsx-h.d.ts, packages/dom-expressions/src/jsx.d.ts
- fix: https://github.com/solidjs/solid/issues/1184 
can also use more strict 
```{ [key: `—${string}`]: string | number | undefined }```
=> fix(type): style use variable type error

packages/lit-dom-expressions/src/index.ts
There was previously a runtime error on empty script/style tags here, because `firstChild` was `null` in those cases, but the type cast assumed it to be non-null and a non-null assertion was being used on a null value. Now the type is casted to nullable, and an optional-chaining operator is used instead of non-null assertion to catch the `null` case.
=> fix runtime error on empty style/script tags

.npmrc, package-lock.json, package.json
This PR implements thoughts at https://github.com/ryansolid/dom-expressions/issues/172:
1. Introducing a new npm script to finish all initialization task.
2. Once the NPM version is not matched, `npm install` will get following error:
```bash
➜  dom-expressions git:(main) ✗ npm run init
> dom-expressions-build@0.31.0 init ~/dom-expressions
> npm install && npm run bootstrap
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for dom-expressions-build@0.31.0: wanted: {"npm":">=7.0.0"} (current: {"node":"14.19.3","npm":"6.14.17"})
npm ERR! notsup Not compatible with your version of node/npm: dom-expressions-build@0.31.0
npm ERR! notsup Not compatible with your version of node/npm: dom-expressions-build@0.31.0
npm ERR! notsup Required: {"npm":">=7.0.0"}
npm ERR! notsup Actual: …
```
=> reliable quick start command to initialize this project

packages/dom-expressions/src/jsx.d.ts
According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog dialog element also supports `cancel` and `close` events
=> Added missing events for dialog element

packages/babel-plugin-jsx-dom-expressions/src/ssr/element.js, packages/babel-plugin-jsx-dom-expressions/test/__ssr_fixtures__/insertChildren/code.js, packages/babel-plugin-jsx-dom-expressions/test/__ssr_fixtures__/insertChildren/output.js
Fixes a problem where passing functions (either arrow functions or function expressions) with a block body would break compilation.
Fixes https://github.com/solidjs/solid/issues/1423
=> fix-dom-function-children

packages/dom-expressions/src/jsx-h.d.ts, packages/dom-expressions/src/jsx.d.ts, packages/dom-expressions/test/verify_types.ts
The idea behind was PR was originally in figuring out where `jsx-runtime` definitions are coming from and apply minimal changes without breaking someones IDE or existing projects. And also adding jsdoc like references to where each element comes from.
Added support template html field. Added `verify_types.ts` file to run extra static checks in an IDE.
This files will override definitions in the solid repository.
Tested with a solid/web tsx files, but I had to temporally change tsconfig.path to make it see this files.
=> Reorganize jsx-runtime html/svg type definitions 

packages/babel-plugin-jsx-dom-expressions/src/shared/component.js
Normalize TypeScript `satisfies` expression along with `!` and `as`
=> normalize TS satisfies expression

packages/dom-expressions/src/jsx-h.d.ts, packages/dom-expressions/src/jsx.d.ts
There might be other types missing, I just stumbled on this in my project. See [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href)
I am uncertain about the implications of `FunctionMaybe` type but I followed example of similar attribute typing.
=> fix: add href attribute to GradientElementSVGAttributes interface

packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/src/dom/template.js, packages/babel-plugin-jsx-dom-expressions/src/shared/transform.js, packages/babel-plugin-jsx-dom-expressions/src/ssr/element.js, packages/babel-plugin-jsx-dom-expressions/src/universal/element.js, packages/babel-plugin-jsx-dom-expressions/src/universal/template.js
We should not modify the type of a variable at runtime, this can be error prone and misleading:
```ts
results.decl.unshift(decl);
results.decl = t.variableDeclaration("const", results.decl); // decl's type changed from `array` to `t.VariableDeclaration`
```
To fix this, we can create another property to save the original declarations.
=> refactor: keep persistent type

packages/babel-plugin-jsx-dom-expressions/src/shared/utils.js
`t.cloneDeep` was deprecated at `@babel/types` <sup>[1]</sup>
[1] https://github.com/babel/babel/pull/7149/files#diff-485c64b2cca1542ce531c88388b1d12cabbc7a0ae5846be94c68d3fc81e057d7
=> refactor: do not use deprecated `t.cloneDeep`

packages/babel-plugin-jsx-dom-expressions/README.md
**Reasoning**
- based on this example I was pretty confused when playing around with certain playground implementations as they generally had different output then I'd expect based on the example here. After doing a minimal repo to try and see why the code examples differ I found that the docs didn't seems correct anymore (either due to implementation drift or due to the default configurations not being proper to get the documented output) If the case is the former then I think we should update it. If the case is the latter we should add the configs to the README.md example (and I'd be happy to do that).
**To Test**
- I'd encourage anyone to test a blank project against the example and make sure they get the same output as I did.
**Place for feedback**
-
- Not sure if the …
=> fix (docs): updated "compiles to" code example for babel-plugin-jsx-dom-expressions

packages/dom-expressions/src/jsx-h.d.ts, packages/dom-expressions/src/jsx.d.ts
**Summary:**
I've added the missing `pathLength` to the `ShapeElementSVGAttributes` interface
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pathLength
=> fix: pathLength added to ShapeElementSVGAttributes

packages/dom-expressions/src/jsx.d.ts
Relevant [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/enterkeyhint).
Inferno [has it](https://github.com/infernojs/inferno/blob/e7f9f4e902a4daaf69e61693b1265f2558f210a6/packages/inferno/src/core/types.ts#L1188) since [Feb last year](https://github.com/infernojs/inferno/commit/696006c3d817fc4f0af45d422eb78ad6deeb1caa)
=> fix: add enterkeyhint attribute to InputHTMLAttributes interface

packages/dom-expressions/src/universal.d.ts
The use function needs to be exported by universal renderers, but was not defined in the Renderer type definition. This causes type errors when building a universal renderer in Typescript.
Here I added a type-definition based on the definition of the use function in universal.js
=> Add type definition for Universal Renderer use function

packages/dom-expressions/src/jsx.d.ts
Referring to this issue https://github.com/solidjs/solid/issues/1642 I added non-standard attributes (see this https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search#non-standard_attributes).
=> Supported non-standard input attributes

packages/dom-expressions/src/jsx.d.ts
Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#loading
From https://github.com/solidjs/solid/pull/1652
=> Add `loading` JSX attribute type to `<iframe>`

packages/dom-expressions/src/server.js
- `prop` was declared as `const`, and it was being mutated in the `attr:` check of `ssrSpread`
=> Fix prop mutation error on `attr:`

packages/dom-expressions/package.json, pnpm-lock.yaml
This is just a patch.
seroval 0.5.0 had some broken serialization-related stuff but mainly on Typed arrays. seroval has also added support for 8 new types. There are no breaking changes though.
=> Bump seroval to 0.7.0

packages/dom-expressions/src/constants.js
As mentioned [here](https://github.com/solidjs/solid/issues/1713) heading tags are currently not included in DOMElements. This pr adds h1-h6 to the constant.
=> add heading tags to const DOMElements

packages/dom-expressions/src/jsx.d.ts
I see there was an [Issue](https://github.com/solidjs/solid/issues/1690) about missing properties, but I suppose they should be optional, because if I do 
```ts
import type { JSX } from 'solid-js';
type ImgAttrs = JSX.ImgHTMLAttributes<HTMLImageElement>;
const defaultProps = {
src: 'http://'
} satisfies ImgAttrs;
```
I get a error that `elementtiming` and  `fetchpriority` is required
=> Make `elementtiming` and  `fetchpriority` optional properties

packages/dom-expressions/src/jsx.d.ts
Already exists on` <input>` but not on `<textarea>`. 
https://html.spec.whatwg.org/multipage/interaction.html#input-modalities:-the-enterkeyhint-attribute
=> Add enterkeyhint to textarea type def

packages/dom-expressions/src/jsx-h.d.ts, packages/dom-expressions/src/jsx.d.ts
=> fix names of `http-equiv` and `accept-charset` attributes

packages/babel-plugin-jsx-dom-expressions/src/shared/component.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/components/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/components/output.js
As per pull request title, unwraps arrow function IIFEs if they are directly used within a component prop.
the following `<Show />` pattern can be quite common, and this saves up some of the bytes incurred by it
```jsx
<Show
when={(() => {
const val = value();
if ("key" in val) {
return val;
}
})()}
>
{(val) => (
<>
...
</>
)}
</Show>
```
=> Unwrap arrow function IIFEs in component props

packages/dom-expressions/package.json, packages/dom-expressions/src/serializer.d.ts, packages/dom-expressions/src/serializer.js, packages/dom-expressions/src/server.js, pnpm-lock.yaml
This is a work-in-progress. This PR integrates seroval's new streaming serializer to be utilized by SolidJS as a whole. With the new serializer, SolidJS will be able to:
- Dedupe references in both nested objects and across resources
- Allows SolidJS to serialize `Promise` and `ReadableStream` instances 
- Allow nested `Promise` instances to be naturally deferred (only top-level `Promise` instances can be blocked). These instances are then serialized and streamed later on.
- Part of the HydrationScript would be delegated to seroval as seroval has its own "hydration" script.
=> feat: streaming serializer

packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/SVG/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/customElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/eventExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/simpleElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/textInterpolation/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/SVG/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/customElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/eventExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/simpleElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/textInterpolation/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/SVG/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/customElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/eventExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/simpleElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/textInterpolation/output.js, pnpm-lock.yaml
This PR attempts to shave more bytes off the template code by removing or replacing the quotes, along with removing the spacing between them when it's next to a quoted attribute value.
The code would eagerly use single quotes when it can't remove the quotes entirely, this is mostly because the template literals would usually be converted into regular string by the transformer/minifier, where they would normally be double quotes. I think by doing this, gzip compression would atleast see that there are more repetitions with `("`, but that's something that has yet to be tested.
The one thing I haven't done here is to adjust `escapeHTML` code, as it still assumes that it's being wrapped in a double quote. I wasn't sure how to deal with it, so I just kept it as is but it'd definitely have to …
=> Shave bytes by removing quotes and spacing from attributes

packages/babel-plugin-jsx-dom-expressions/src/shared/component.js, packages/babel-plugin-jsx-dom-expressions/src/shared/transform.js
- Fixes #293 
- Fixes #292
Example:
```js
class Example {
template = () => (
<this.H1
onClick={() => this.foo()}
onLoad={(function () {
console.log(this)
}).bind({ foo: 'bar' })}
>
<h1 onClick={() => this.bar()}>{this.title}</h1>
<this.Child onClick={() => this.bar()}>{this.title}</this.Child>
</this.H1>
)
}
```
Output:
```js
var _client = require("../../src/client");
const _tmpl$ = /*#__PURE__*/(0, _client.template)(`<h1>`);
class Example {
template = () => {
const _self$ = this;
return (0, _client.createComponent)(this.H1, {
onClick: () => _self$.foo(),
get onLoad() {
return function () {
console.log(this);
}.bind({
foo: 'bar'
});
},
get children() {
return [(() => {
const _el$ = _tmpl$();
_el$.$$click = () => _self$.bar();
(0, _client.insert)(_el$, () => _self$.title);
return _el$; …
```
=> Fix `this` compilation

packages/babel-plugin-jsx-dom-expressions/src/shared/utils.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/output.js
Fixes https://github.com/ryansolid/dom-expressions/issues/283
=> feat: don't consider ns import as dynamic

packages/dom-expressions/src/server.js
This adds a new internal method called `push`. It's alternative to `serialize` except that this one has a very specific purpose: islands generation.
=> feat: `push`

packages/babel-plugin-jsx-dom-expressions/src/dom/template.js, packages/babel-plugin-jsx-dom-expressions/src/shared/utils.js, packages/babel-plugin-jsx-dom-expressions/src/universal/template.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/SVG/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/customElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/SVG/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/customElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/SVG/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/customElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__universal_fixtures__/attributeExpressions/output.js
- Use a custom base54 identifier instead of Babel's unique identifiers for the object properties
=> Smaller identifiers for merged dynamics

packages/dom-expressions/package.json, packages/dom-expressions/src/serializer.js, pnpm-lock.yaml
The Web API support in seroval has been moved to another package, `seroval-plugins`. This PR makes it so that seroval 1.0 is supported, while also adding the `seroval-plugins` package as a new dependency.
=> Move to seroval 1.0

packages/dom-expressions/src/server.js
Fixes the behavior that you can observe here: https://stackblitz.com/edit/solid-ssr-vite-juconn?file=src%2Fpages%2FHome.tsx where if you put a string that contains a double quote into the style attribute of an element, the server side rendered version isn't correctly escaped. Example: `<main data-hk="0.0.0.2.13.0.0.6.0.0.0.0.0.1"><h2 style="--my-var: url("./test.svg");">Home!</h2></main>`
Edit: fix wasn't as easy as I thought, gotta improve this a lil
=> Correctly escape style attribute in SSR output

packages/dom-expressions/src/client.js
This is to get tree shaking when using SolidStart's `getRequestEvent()` function e.g.
```js
export default () => {
const requestEvent = getRequestEvent()
if (requestEvent) {
// server code here
}
// ...
}
```
For some reason Rollup can't statically analyse a function without an explicit return value. So before this change, the server code gets bundled into the client, but after this change, Rollup is able to see that `getRequestEvent()` always returns `undefined` meaning that `requestEvent` is always `undefined` meaning that the if statement can be tree shaken away for the client build.
=> make `voidFn()` return value explicit

packages/dom-expressions/src/client.js
When the element passed to `render` doesn't exist, it shows a cryptic `element is null`. Improve that with a friendly message. 
I'm not sure what `sharedConfig.context` do, followed it is used in similar places.
=> Friendly message for when mount point doesn't exists

packages/dom-expressions/src/jsx-h.d.ts, packages/dom-expressions/src/jsx.d.ts
Closes https://github.com/solidjs/solid/issues/2052
=> fix(dom-expressions): type of SVG `<use>`

packages/dom-expressions/src/client.js
fixes https://github.com/solidjs/solid/issues/2136
i'm not sure if `untrack(() => props.ref(node))` is better
=> fix(dom-expressions): proper ref handling in spread

packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/src/universal/element.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__ssr_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__ssr_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__ssr_hydratable_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__ssr_hydratable_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__universal_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__universal_fixtures__/attributeExpressions/output.js
fixes https://github.com/solidjs/solid/issues/2137
these are still relevant here so didn't touch them
```jsx
let refTarget;
const template8 = <div ref={refTarget} />;
```
```jsx
const template10 = <div ref={refFactory()} />;
```
not sure why the check for call expression was there though.
=> fix(dom-expressions): handle expression in ref

packages/dom-expressions/src/client.js
On this example, the node flashes on the dev tools because its failing the equality check, as whats on the dom is a string and the new value is a number https://playground.solidjs.com/anonymous/abf375c1-7f30-4d09-bf19-e543a5681e70
quoting from a discord message
> That's happening because it's failing this triple equality check https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/client.js#L409 , as what's rendered is the 0 string and the new data is 0 the number. It's then converted to a string https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/client.js#L416
but then it's not compared when updating on this case https://github.com/ryansolid/dom-expressions/blob/main/packages/dom-expressions/src/client.js#L425C26-L425C41
If …
=> avoid updating text node if value is the same after converting to a string

packages/babel-plugin-jsx-dom-expressions/src/shared/component.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/components/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/components/output.js
- Adds test for an IIFE with a parameter
- Adjust the transformation so unwrapping only happens when there isn't any
=> Don't unwrap IIFE if it contains parameters

packages/dom-expressions/src/jsx-h.d.ts, packages/dom-expressions/src/jsx.d.ts
The new [Toggle events](https://developer.mozilla.org/en-US/docs/Web/API/ToggleEvent) are available on any element with a valid `popover` attribute, as well as previously [on `<details>`](https://github.com/ryansolid/dom-expressions/pull/110)
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/toggle_event
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforetoggle_event
=> Add onToggle and onBeforeToggle handlers

.github/workflows/main-ci.yml, packages/dom-expressions/package.json, pnpm-lock.yaml
Note: probably at some point we need to re-expose the serialization API so that SolidStart can sync seroval (and it's plugin configuration) instead of installing it separately.
=> Bump `seroval` to `1.1.0`

packages/dom-expressions/src/jsx-h.d.ts, packages/dom-expressions/src/jsx.d.ts
Source: https://developer.mozilla.org/en-US/docs/Web/API/HTMLSourceElement
=> add `width` and `height` attributes to `SourceHTMLAttributes`

packages/babel-plugin-jsx-dom-expressions/src/ssr/element.js, packages/dom-expressions/src/constants.js
1. It saves 5+ bytes for every single attribute that's instead set as a property, so I've added a list of [reflected attributes](https://html.spec.whatwg.org/#reflected-idl-attribute) to the Properties list.
1. Fix 1 typo in a comment
```tsx
render(
() => (
<>
<a id={Math.random() > 0.5 ? 'linkA' : 'linkB'}>link</a>                   {/* id */}
<button name={Math.random() > 0.5 ? 'name a' : 'name b'}>name btn</button> {/* name */}
<link rel={Math.random() > 0.5 ? 'preload' : 'preconnect'}>link</link>     {/* rel */}
<input type={Math.random() > 0.5 ? 'text' : 'password'} />                 {/* type */}
</>
),
document.body
);
```
```js
(() => {
return [
((c = G()), e(() => a(c, 'id', Math.random() > 0.5 ? 'linkA' : 'linkB')), c),
((r = k()), e(() => a(r, 'name', Math.random() > 0.5 ? …
```
=> Prefer to set property when property & attribute are identical

packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/dom-expressions/src/client.js, packages/lit-dom-expressions/src/index.ts
It adds a few checks for `is` in attributes/props to mark the element as a custom element. 
fixes https://github.com/solidjs/solid/issues/2122
still there's a need to take into account spreads
=> `is` in element attributes/props counts as custom element

packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/src/shared/utils.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/customElements/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/customElements/output.js, packages/dom-expressions/src/client.d.ts, packages/dom-expressions/src/client.js, packages/dom-expressions/src/jsx-h.d.ts, packages/dom-expressions/src/jsx.d.ts, packages/dom-expressions/src/server.js
The idea of the `bool:` namespace is to control if an attribute is present or not by evaluating its value to truthy/falsy. If it is truthy the attribute is added with an empty string as value, and if falsy the attribute is removed.  It's similar to `BooleanAttributes` that dom-expressions already considers but controllable by the user. This is specially relevant in the web components world where names are arbitrary and cannot be known beforehand.
The namespace will make the intention clear and this cannot be done with dom-expressions `setAttribute`.
I am running into an issue trying to implement this feature and your help would be welcome
I have added 1 test for "custom elements" 
`babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/customElements/code.js`
When I run `npm run test` it …
=> preliminary support for `bool:` [needs help]

packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/src/dom/template.js, packages/babel-plugin-jsx-dom-expressions/src/shared/preprocess.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/output.js, packages/dom-expressions/src/client.js, packages/lit-dom-expressions/src/index.ts
This attempts to reuse the same logic as `hasCustomElement` as an `isImportNode`. That currently only becomes `true` when an `image/iframe` has the attribute `loading="lazy"` 
To solve https://github.com/solidjs/solid/issues/1828 avoiding using `document.importNode` for every other element.
This in theory should have worked on the first try. For some reason nested elements with such an attribute won't be marked as `isImportNode`. Handled this oddity with a _least resort_ regexp for now.
`_$template('<img src=""loading=lazy>', true, false),`
`_$template('<div><img src=""loading=lazy>', true, false);` 
Without the regexp the last one won't have `true, false)`
=> use `document.importNode` for when `img/iframe` use `loading="lazy"`

packages/dom-expressions/src/jsx.d.ts
Update element interface for `menu`, closes https://github.com/solidjs/solid/issues/2257
=> Update type on `menu`

packages/dom-expressions/src/jsx-h.d.ts, packages/dom-expressions/src/jsx.d.ts
It adds the namespaced version of the default events. such `on:click`. There is probably some clever way to avoid duplication, but I preferred to follow how is it done. 
I'm not sure what will happen if someone tries to define an event with the same name, I suppose we can move the location of the `extends CustomEventHandlersNamespaced<T>` if that's reported as an issue.. and that will fix it? 🤔 
Somehow prettier formatted the jsdoc comments, I suspect a plugin I have installed, it shouldn't cause issues with the regular formatting as it won't touch comment contents.
closes https://github.com/solidjs/solid/issues/1939
asked for input in the TS channel and seems like a good idea to include this https://discord.com/channels/722131463138705510/783844647528955931/1291147473011736613
=> add default namespaced events

packages/babel-plugin-jsx-dom-expressions/package.json, packages/babel-plugin-jsx-dom-expressions/src/shared/validate.js
Issue: jsdom imports a ton of stuff. This is usually not a problem as it's been treeshaked from the different build tools. But it causes an issue when you are trying to use the `babel-solid-preset` entirely in the browser. For example `jsdom` imports `child_process`, that just doesn't exist in the browser, and places like `esm.sh` cannot treeshake it because it doesn't know if it is going to be used or not. This is causing problems to projects like https://github.com/bigmistqke/repl and possibly some others.
Upon investigation, it seems that `jsdom` it's using behind the scenes `parse5`. So trying to slim down the dependencies I replaced it with that.  This also gives me more confidence into the approach taken to validate the HTML because the functions from `parse5` actually claim they …
=> slim down `jsdom` dependency to `parse5`

packages/babel-plugin-jsx-dom-expressions/src/shared/validate.js
Adds to the validation `th/thead/tbody` which were missing.
Then, we were considering the inner bits as `tr/td`, but didn't consider the outer bits as empty `table/thead/body`, so this is now considered.
The switch case is probably not needed, as it will validate, but maybe could be nice to have a section of skips, it could improve performance.
A bit verbose, but I hope that's all for tables
=> Update special cases for tables

packages/babel-plugin-jsx-dom-expressions/src/shared/postprocess.js
It adds a change to respect `validate` setting from config for the new validation of whole partials
closes https://github.com/ryansolid/dom-expressions/issues/359
=> respect `validate` config setting for validation of whole partial

packages/babel-plugin-jsx-dom-expressions/src/shared/validate.js
This is a small change, but tagNames could contain `:` such `<kilo:svg/>`, this is used sometimes in XML documents, and such a tagName will cause a fail on the removal of attributes and therefore validation as a whole.
=> tagName could have `:` such `<kilo:svg>` 

packages/dom-expressions/src/server.js
We are using Solid to generate internal emails and to avoid the unnecessary `data-hk` attributes I wrap them in `<NoHydration>`. This sometimes caused errors to be thrown so we are using this patch in production to avoid that.
=> fix throwing an error when using `<NoHydration>` before `sharedConfig.context` is initialised

packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/src/shared/component.js, packages/babel-plugin-jsx-dom-expressions/src/universal/element.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/components/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/components/output.js, packages/babel-plugin-jsx-dom-expressions/test/__universal_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__universal_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__universal_fixtures__/components/code.js, packages/babel-plugin-jsx-dom-expressions/test/__universal_fixtures__/components/output.js
fixes https://github.com/solidjs/solid/issues/2313
=> fix imported binding ref

packages/dom-expressions/src/jsx.d.ts
This just makes the `classList` attribute a little more convenient to work with for those who have `exactOptionalPropertyTypes` turned on in their `tsconfig.json`.
=> loosen `classList` attribute type

packages/babel-plugin-jsx-dom-expressions/package.json, packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/src/shared/postprocess.js, packages/babel-plugin-jsx-dom-expressions/src/shared/validate.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/output.js
Couple of fixes and improvements for the HTML validation:
- do not collect attributes in `results.templateWithClosingTags`  https://github.com/solidjs/solid/issues/2338
- add `tfoot` to table special cases
- add  `col/colgroup` to table special cases https://github.com/solidjs/solid/issues/2338#issuecomment-2423415856
- improve message output when it errors. I found the "diff" very hard to understand, it makes the message more explicit now showing "User HTML", "Browser HTML" and "Original HTML".
=> HTML validation fixes

packages/dom-expressions/src/server.js
Related to https://github.com/solidjs/solid/issues/2339
ssr: namespaced attributes are inlined into the html in some situations
With config option `ssr:true` sometimes(depending on if `<Dynamic ../>` JSX tag was used or not) the namespaced attributes are being written to the html.
For example `<div attr:name="value"/>`  produces the same thing, instead of `<div name="value"/>` 
Investigating, it seems that `attr:` wasn't the only special namespace with problems. This PR includes updates for avoiding inlining of `prop/attr/bool:` namespaces.
`prop/attr:` works in both cases for my tests (dynamic or not)
There's a need to look into `ssrAttribute` because for some reason `bool:` ends inlined when used as `<div bool:name="quack"/>` (this doesn't happen when used as `<Dynamic component="div" …
=> ssr attribute inlining updates

packages/dom-expressions/src/jsx-h.d.ts, packages/dom-expressions/src/jsx.d.ts
See https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement/disablePictureInPicture
And the list of attributes here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video
=> Add disablepictureinpicture attribute to <video> JSX types

packages/babel-plugin-jsx-dom-expressions/src/shared/validate.js
- Adds `caption` to table html validation https://developer.mozilla.org/en-US/docs/Web/HTML/Element/caption
- refactor the replacement
The following two can be closed
- https://github.com/ryansolid/dom-expressions/issues/358
- https://github.com/solidjs/solid/issues/2183
About the last one, I just copy paste the example given and produces a warning as expected:
```html
User HTML:
<div><table><thead><tr>#text</tr></thead><tbody><tr><td>#text</td><td>#text</td></tr></tbody></table></div>
Browser HTML:
<div>#text<table><thead><tr></tr></thead><tbody><tr><td>#text</td><td>#text</td></tr></tbody></table></div>
Original HTML:
<div><table><thead><tr>Name</tr></thead><tbody><tr><td>iPhone</td><td>13</td></tr></tbody></table></div>
```
=> add `caption` to table HTML validation

packages/babel-plugin-jsx-dom-expressions/src/shared/utils.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/fragments/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/fragments/output.js
Fixes https://github.com/solidjs/solid/issues/2377
Without the change, the test compiles to the incorrect
```js
const singleTemplateLiteral = greeting`world`
```
=> Treat tagged templates as function calls

packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/attributeExpressions/output.js
This change, inlines in the template boolean literals. For example
`<el attr={true}/>` becomes  `<el attr/>`
and 
`<el attr={false}/>` becomes  `<el/>`
Considerations:
- this change skips doing this transformation for "custom elements", because as we are defaulting to properties I suspect something will break.
- I do not think this is a breaking change, at least from my tests I didn't see anything that could cause problems.
- this is related to an effort to fix the attributes vs properties problem
The most recent issue illustrating this props vs attr problem comes from https://github.com/ryansolid/dom-expressions/issues/384 In there they are doing `<video playsinline={true} />;`, in production code currently:
- client side works because compiles it to `_el$.playsInline = true;`
- in ssr …
=> inline in template boolean literals

packages/dom-expressions/src/jsx-h.d.ts, packages/dom-expressions/src/jsx.d.ts
Added some more of these attributes that were lacking https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video
I added them in all lower case but as a user I'd prefer the camel cased version.
I can see some attributes are both all lower case and camelCase like here: https://github.com/danieltroger/dom-expressions/blob/0d5c46b24c9fba2d62dee8bc1acbf98c733fa633/packages/dom-expressions/src/jsx.d.ts#L1173-L1174
What's solid-js' convention?
=> Add more video attributes

packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/src/shared/utils.js, packages/babel-plugin-jsx-dom-expressions/src/ssr/element.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/customElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/customElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/customElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/hybrid/output.js, packages/babel-plugin-jsx-dom-expressions/test/__ssr_fixtures__/customElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/__ssr_hydratable_fixtures__/customElements/output.js, packages/dom-expressions/src/client.js, packages/lit-dom-expressions/src/index.ts
It includes two changes:
1. avoids transforming case and dashes for attributes/properties.
2. It doesn't default to `properties` in custom elements. It defaults to `attributes`.
Rationality: Seems like numerous people expect custom elements to just receive attributes  [1](https://discord.com/channels/722131463138705510/1297146159202046003), [2](https://github.com/solidjs/solid/issues/2339), [3](https://github.com/solidjs/solid/discussions/2322#discussion-7274338), [4](https://github.com/solidjs/solid/issues/2321), and they will use `prop:` when they want to set a property. It seems strange wanting to use `prop:`, but it looks to me, they are used to dealing with this sort of problem. Kind of makes sense as attributes can only receive strings.
Avoiding transformation of case and dashes, …
=> attributes/properties transformation & custom elements defaulting to attributes

README.md
This PR brings copy that exists in the Solid Documentation back into `dom-expressions` for users outside of SolidStart.
=> Add XSS notice for end-users

packages/babel-plugin-jsx-dom-expressions/src/ssr/element.js, packages/babel-plugin-jsx-dom-expressions/test/__ssr_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__ssr_fixtures__/attributeExpressions/output.js, packages/dom-expressions/src/server.js
fixes https://github.com/solidjs/solid-start/issues/1598, https://github.com/solidjs/solid-start/issues/1630, https://github.com/solidjs/solid-start/issues/1749
spread is not skipping escaping for script, style tags
this PR handles it
i'll add the tests if this is good to go
=> skip escaping script, style in spread

packages/dom-expressions/src/jsx.d.ts
added common values for \<media> controlslist
added common values for \<input> type
added common values for \<a> target
the rest is prettier formatting
=> better intellisense for target, controlslist and type

packages/babel-plugin-jsx-dom-expressions/README.md, packages/babel-plugin-jsx-dom-expressions/src/config.ts, packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_compatible_fixtures__/SVG/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_compatible_fixtures__/SVG/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_compatible_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_compatible_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_compatible_fixtures__/simpleElements/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_compatible_fixtures__/simpleElements/output.js, packages/babel-plugin-jsx-dom-expressions/test/dom-compatible.spec.js
We're building a UI in a browser-like environment for game engines named [Gameface by Coherent Labs](https://coherent-labs.com/) which [powers many popular titles with millions of players worldwide](https://coherent-labs.com/powered-by-coherent-labs/). Coherent Labs is trying to make Solid the recommended choice for in-game UI developed using Gameface via their [open source UI component library](https://github.com/CoherentLabs/Gameface-UI).
Unfortunately, `dom-expressions` currently makes some omissions when generating templates from JSX that aren't digestible by that browser. Namely, omitting closing tags and quotes, which while [OK according to the HTML spec](https://html.spec.whatwg.org/#attribute-value-(unquoted)-state), [isn't acceptable under the XML …
=> Improve compatibility with more browser-like environments

packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_compatible_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/attributeExpressions/output.js
Undo #385 that inadvertently introduced a breaking change for 1.9.x, by changing the behaviour of things like `<div draggable={true}/>` to be `<div draggable/>` instead of the current `<div draggable="true"/>`., this also affects other attributes as `aria-hidden`, etc.
However, the change undid here is already applied and desired in `next`, as that's the behaviour we want for Solid 2.0
=> main: undo inline in template boolean literals #385

packages/lit-dom-expressions/src/index.ts
=> Pass property names as quoted strings.

packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_compatible_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_compatible_fixtures__/attributeExpressions/output.js
The following worked: 
```js
const div = <div prop:poster="test"></div>;
```
https://playground.solidjs.com/anonymous/4ecb5e58-9d49-48cd-b088-cd01116b24d1
but the following gives an error
```js
const div = <div><div prop:poster="test"></div></div>;
```
https://playground.solidjs.com/anonymous/d717fcfe-1aca-48fa-ba89-5f38fa6f8d91
--- 
Was hard to trace it down but figured the problem was `results.id` being undefined because of `info.skipId`  which calls `detectExpressions`.  
`detectExpressions` seems to try to skip when is a string/number.  
https://github.com/ryansolid/dom-expressions/blob/main/packages/babel-plugin-jsx-dom-expressions/src/dom/element.js#L1105-L1110
I saw there's a case for the "use" namespace, so added the others too `attr/prop/bool` and that seems to have worked.
edit: …
=> fix prop/attr namespace error on children when value is a string

packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_compatible_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_compatible_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__ssr_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__ssr_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/dynamic-hydratable.spec.js
`setProperty` by hydration, was not using `PropAliases`, so it was setting the wrong property when the user gives a property name that doesn't match the real one (giving a lowercase instead of the `camelCase` for example)
This was originally reported in https://github.com/ryansolid/dom-expressions/issues/384, but somehow I missed the root cause. Using the playground to test some prop/attr stuff noticed this was the issue.  
This should fix it for good, cc @danieltroger
=> fix hydration `setProperty` not using `PropAliases`

packages/babel-plugin-jsx-dom-expressions/rollup.config.js, packages/babel-plugin-jsx-dom-expressions/src/shared/preprocess.js
We have been using parse5 for a while for validating tag nesting, it _simulates_ a browser and seems to be enough.
`validate-html-nesting` doesnt seem to support math and is causing errors.  https://github.com/ryansolid/dom-expressions/issues/424 
Somehow whitespace changed, may use this link for the diff https://github.com/ryansolid/dom-expressions/pull/427/files?diff=unified&w=1
=> remove `validate-html-nesting` package

packages/dom-expressions/src/jsx-h.d.ts, packages/dom-expressions/src/jsx.d.ts
This update revisits relationship between interfaces., and global attributes.
- `ElementEventMap` is not needed, there are three categories of events: global events, window events, and events that only exists for an element.
- remove global attributes from elements and add these in `DOMAttributes` or similar
- misc updates
`CustomAttributes` = framework attributes/properties
`DOMAttributes` = `Element` and `Node` interface attributes/properties
Changed relation to be:
`<div>` -> HTMLAttributes -> DOMAttributes
`<svg>` -> CoreSVGAttributes  -> DOMAttributes
`<math>` -> MathMLAttributes-> DOMAttributes
This way we are not adding stuff we shouldn't be adding to elements.
=> main: JSX types update

packages/babel-plugin-jsx-dom-expressions/src/shared/validate.js
I have found that the tag `foreignObject` vs `foreignobject` causes problems. 
For whatever reason, I cannot seem to be able to reproduce anymore. I dont know if chrome or parse5 changed anything. 
In any case the casing of tags is not something we are interested to test, its the nesting, so the comparator lowercases both strings.
=> ignore case when validating tag nesting

packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_compatible_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/attributeExpressions/output.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/attributeExpressions/output.js
This improves on the current optimization of inlining styles by inlining also:
1. when is an object, the key is a string, and value is string/numeric
2. remove properties from object when value is undefined/null
There is already implemented a preprocess styles, but I am not confident to change it and just wanted to add 1 more step.  I tried to add it after, but everything kept breaking, so I just added it before.
This optimization was motivated by the eslint plugin for solid, because for whatever reason autoformat makes of the style attribute an object. 
For example, you go to the playground and paste the following it will complain `style` is a string.
```js
const div = <div style="background:red;" />;
```
=> inline style when is an object of string/numeric values

packages/babel-plugin-jsx-dom-expressions/src/dom/element.js, packages/babel-plugin-jsx-dom-expressions/src/shared/utils.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/attributeExpressions/code.js, packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/attributeExpressions/output.js
When object is just an identifier it was not adding the effect, such `<div style={style} classList={classes}/>`.
This considers `@once`, for in case It's desired to bail out from the effect.
=> fix regression with inlining of `style` and `classList` 

packages/dom-expressions/src/jsx-h.d.ts, packages/dom-expressions/src/jsx.d.ts
fix `closedby` type missing optional in `<dialog/>` element
see https://github.com/solidjs/solid/issues/2524
=> main: update JSX types

packages/dom-expressions/src/jsx-h.d.ts, packages/dom-expressions/src/jsx.d.ts
- mark `closedby` as optional
- remove some types related to `attr:` and `bool:`
=> next: update JSX Types
