ryansolid/dom-expressions

- packages/dom-expressions/src/runtime.js
Log value separately, console will handle it's visualisation
>  Log value separately 

- packages/babel-plugin-jsx-dom-expressions/src/dom/element.js
- packages/babel-plugin-jsx-dom-expressions/src/shared/component.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/code.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/output.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/components/code.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/components/output.js
fix: https://github.com/ryansolid/solid/issues/203
> fix: transform callExpression ref

- packages/babel-plugin-jsx-dom-expressions/src/shared/utils.js
- packages/dom-expressions/src/runtime.js
See https://github.com/ryansolid/dom-expressions/pull/27#issuecomment-690537305 for more info
> Remove g flag from escape regex, fixes #27

- packages/dom-expressions/src/jsx.d.ts
> add aria attributes

- packages/dom-expressions/test/dom/classList.spec.jsx
In my opinion, adding test to make sure props `classList`, `class` and
`className` work well toghter is important.
WIP.
> test: Add test for classList

- .gitignore
- packages/babel-plugin-jsx-dom-expressions/package.json
- packages/hyper-dom-expressions/package.json
- packages/lit-dom-expressions/package.json
- packages/lit-dom-expressions/src/index.ts
- packages/lit-dom-expressions/test/html.spec.js
fixes #143
The PR has whitespace changes from prettier in the test file. Turn on "Hide whitespace" setting when viewing the diff.
> Handle special case attributes

- packages/dom-expressions/src/client.d.ts
Main PR with explanations: https://github.com/solidjs/solid/pull/1139
> fix: add explicit js extension to jsx

- packages/dom-expressions/src/server.js
- packages/dom-expressions/test/ssr/ssr.spec.js
Had this show up in a build on my own project the other day (`ReferenceError: results is not defined`) and it looked easy enough to fix, I also added a simple test case to recreate the error/verify the fix.
> Fix undefined variable in SSR spread

- packages/dom-expressions/src/jsx-h.d.ts
- packages/dom-expressions/src/jsx.d.ts
This fixes https://github.com/solidjs/solid/issues/1184#issuecomment-1231060775
Signed-off-by: yw662 <yw662@njit.edu>
> fix a typo (— to -)

- packages/babel-plugin-jsx-dom-expressions/README.md
1. Improve config documentations;
2. Fixed some typos.
> docs(babel-plugin-jsx-dom-expressions): improve config

- packages/babel-plugin-jsx-dom-expressions/src/dom/element.js
might fix https://github.com/solidjs/solid/issues/1330
> fix spread

- packages/dom-expressions/src/client.js
- packages/dom-expressions/src/constants.d.ts
- packages/dom-expressions/src/constants.js
> Support prop: and attr: in spread(), make prop alias element-aware

- packages/babel-plugin-jsx-dom-expressions/src/universal/element.js
> Add missing transformCondition import

- packages/babel-plugin-jsx-dom-expressions/src/dom/element.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/SVG/output.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/code.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/output.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/SVG/output.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/attributeExpressions/output.js
- packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/SVG/output.js
- packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/attributeExpressions/output.js
if the variable is null or undefined then remove this style
https://github.com/solidjs/solid/issues/1299
> add conditions to the style

- packages/babel-plugin-jsx-dom-expressions/src/dom/element.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/code.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/output.js
> Fix class:foo={undefined}/classList={{foo: undefined}} bugs

- packages/dom-expressions/src/jsx.d.ts
- [`inert`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert) global attribute
- [`hidden`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden) global attribute: `until-found` (new) and `hidden` (missing) value
> Add some JSX attribute types

- packages/dom-expressions/src/jsx.d.ts
Adds a few missing transition events
> adds missing transition events

- packages/dom-expressions/src/jsx-h.d.ts
- packages/dom-expressions/src/jsx.d.ts
fix https://github.com/ryansolid/dom-expressions/issues/273
> add `media` property for `MetaHTMLAttributes` interface

- packages/lit-dom-expressions/src/index.ts
See https://github.com/ryansolid/dom-expressions/issues/279
> Fix return type of  `classList`

- packages/dom-expressions/src/constants.js
Hit this snag while developing a custom modal component involving inert attribute
Closes #281
> Add inert as a boolean attribute

- packages/dom-expressions/src/jsx.d.ts
fixes #https://github.com/solidjs/solid/issues/1972
> fix: add missing width property in type

- packages/babel-plugin-jsx-dom-expressions/src/dom/element.js
- packages/babel-plugin-jsx-dom-expressions/src/ssr/element.js
- packages/babel-plugin-jsx-dom-expressions/src/universal/element.js
> chore: fix incorrect usage

- packages/babel-plugin-jsx-dom-expressions/src/shared/transform.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/components/code.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/components/output.js
related https://github.com/ryansolid/dom-expressions/pull/295
fixes https://github.com/solidjs/solid/issues/2141
Not adding tests to other modes as it's essentially the same.
> fix `this` compilation inside class methods

- packages/hyper-dom-expressions/src/index.ts
- packages/hyper-dom-expressions/test/hyperscript.spec.js
> Support a combination of classes defined with dot syntax and as property

- packages/babel-plugin-jsx-dom-expressions/src/shared/transform.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/components/code.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/components/output.js
follow up to https://github.com/ryansolid/dom-expressions/pull/318
> fix `this` compilation inside class fields

- packages/dom-expressions/src/client.js
Opening this in case we need to keep the compiler in https://github.com/ryansolid/dom-expressions/pull/332
> fix props.ref assignment

- packages/dom-expressions/src/jsx.d.ts
> make optional attributes accept undefined when exactOptionalPropertyTypes is enabled

- packages/dom-expressions/src/jsx-h.d.ts
- packages/dom-expressions/src/jsx.d.ts
Added the (possibly forgotten?) BoolAttributes and fixed the on:* attributes type..
> Fix in DOMAttributes

- packages/babel-plugin-jsx-dom-expressions/src/dom/element.js
- packages/babel-plugin-jsx-dom-expressions/src/shared/utils.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/code.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/attributeExpressions/output.js
Related to https://github.com/solidjs/solid/issues/1828#issuecomment-2429672721
Always use `importNode` bit for `img` and `iframe` with attribute `loading` regardless of its value.
> loading lazy with dynamic value

- .github/workflows/main-ci.yml
same as https://github.com/ryansolid/dom-expressions/commit/ff6a1860aa3a6e14be39ffc4200156b3e7050623
> fixes CI for next branch

- packages/babel-plugin-jsx-dom-expressions/src/shared/utils.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/conditionalExpressions/code.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_fixtures__/conditionalExpressions/output.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/conditionalExpressions/code.js
- packages/babel-plugin-jsx-dom-expressions/test/__dom_hydratable_fixtures__/conditionalExpressions/output.js
- packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/conditionalExpressions/code.js
- packages/babel-plugin-jsx-dom-expressions/test/__dynamic_fixtures__/conditionalExpressions/output.js
- packages/babel-plugin-jsx-dom-expressions/test/__universal_fixtures__/conditionalExpressions/code.js
- packages/babel-plugin-jsx-dom-expressions/test/__universal_fixtures__/conditionalExpressions/output.js
Im really unsure about this one, but in theory it applies this https://github.com/solidjs/solid/issues/2498
/cc @mizulu
> wrap member in memo for conditionals 
